/* generated by unplugin-react-components */
export {}
declare global{
	const App: typeof import('./src/App')['App']
	const Notice: typeof import('./src/components/notice')['Notice']
	const Page: typeof import('./src/components/a/page')['Page']
}